parameters:
#    store_marketing.example.class: Store\MarketingBundle\Example

services:
#    store_marketing.example:
#        class: %store_marketing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
