parameters:
#    store_order.example.class: Store\OrderBundle\Example

services:
#    store_order.example:
#        class: %store_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
