# This file is production specific
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: cosmetics
    database_user: root
    database_password: error!2101CWX
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: makeupcosmetics.eu@gmail.com
    mailer_password: error!2758CWX
    locale: fr
    secret: 5><Z>]s19LG6F(8Egzo>87D1`JD;Ta
    ogone_pspid: ClaudeHaest
    ogone_sha1_in: bqTBKC88VxTn_:15
    ogone_sha1_out: i9+kR4vNOt,D:13eFGH
    ogone_mode: prod
