parameters:
#    store_shipping.example.class: Store\ShippingBundle\Example

services:
#    store_shipping.example:
#        class: %store_shipping.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
