store_shipping:
    resource: "@StoreShippingBundle/Controller/"
    type:     annotation
    prefix:   /admin

store_address:
    resource: "@StoreAddressBundle/Resources/config/routing.yml"
    prefix:   /

store_country:
    resource: "@StoreCountryBundle/Controller/"
    prefix:   /admin
    type: annotation

store_customer:
    resource: "@StoreCustomerBundle/Resources/config/routing.yml"
    prefix:   /

store_front:
    resource: "@StoreFrontBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

store_core:
    resource: "@StoreCoreBundle/Controller/"
    type:     annotation
    prefix:   /admin

store_product:
    resource: "@StoreProductBundle/Controller/"
    type:     annotation
    prefix:   /admin

# FosUser
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

