parameters:
#    store_customer.example.class: Store\CustomerBundle\Example

services:
  store.customer_manager:
    class: Store\CustomerBundle\Manager\CustomerManager
    arguments: [@doctrine.orm.entity_manager, @security.context]
#    store_customer.example:
#        class: %store_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
