parameters:
#    store_contact.example.class: Store\ContactBundle\Example

services:
#    store_contact.example:
#        class: %store_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
