parameters:
#    store_country.example.class: Store\CountryBundle\Example

services:
#    store_country.example:
#        class: %store_country.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
